- README.md
- lib/multi.js
- lib/redis-mock.js
- test/redis-mock.multi.js
Not sure if I should also have added support for batch() as it's nearly the same, but not transactional.
For the same reason, did not add support for multi.exec_atomic()
> added support for multi()

- lib/redis-mock.js
- test/redis-mock.strings.test.js
> Add support for PX option within SET command

- lib/list.js
- lib/multi.js
- lib/redis-mock.js
- test/redis-mock.list.test.js
This pull request adds an implementation of ltrim.
> ltrim operation

- lib/hash.js
- test/redis-mock.hash.test.js
Also fixed a few errors that were found by linting.
> hset and hmset should be running toString on all values

- lib/redis-mock.js
- test/redis-mock.connection.test.js
> re issue #30 - use MockInstance._callCallback

- README.md
- lib/multi.js
- lib/redis-mock.js
- lib/strings.js
- test/redis-mock.strings.test.js
> Adding mset & msetnx.

- lib/multi.js
- lib/redis-mock.js
- lib/set.js
- test/redis-mock.set.test.js
Hey, we needed support for SMOVE so added an implementation - attached if you'd like it upstream.
> Add SMOVE support

- lib/helpers.js
- lib/redis-mock.js
- lib/set.js
- test/redis-mock.set.test.js
node-redis is using this, so I added the implementation here.
https://redis.io/commands/srandmember
> Added SRANDMEMBER functionality

- lib/keys.js
- lib/list.js
This should fix the issue reported in #23.
Signed-off-by: Ryan Dy <rdy@pivotal.io>
> Make sure to unref timers when possible

- README.md
- lib/keys.js
- lib/redis-mock.js
- test/redis-mock.keys.test.js
Added support for scan command
make test and make check-tests passing (except for the issues before this PR)
> Added scan command

- README.md
- lib/keys.js
- lib/redis-mock.js
- test/redis-mock.keys.test.js
closes #59 I made earlier today. I wrote some tests as well, let me know if there is anything to do!
> add rename command

- README.md
- lib/multi.js
- lib/redis-mock.js
- test/redis-mock.batch.test.js
- test/redis-mock.multi.test.js
- Piggyback batch on multi
- Rename multi test file to match other tests
- Fix minor linting issues
Tests for batch duplicate tests for multi except error handling in discard.
> Add batch, exec_atomic

- README.md
- lib/keys.js
- lib/redis-mock.js
- test/redis-mock.keys.test.js
> Add renamenx command

- .gitignore
- README.md
- lib/keys.js
- lib/redis-mock.js
- lib/sortedset.js
- test/redis-mock.keys.test.js
- test/redis-mock.sortedset.test.js
Hi - I've added partial support for `ZUNIONSTORE` to the extent that my codebase uses this feature. I don't have time to complete support for `WEIGHTS` or `AGGREGATE` today, but I thought this might already be useful to people, perhaps easy for somebody to quickly add etc.
> Initial support for ZUNIONSTORE (incomplete, no WEIGHTS and AGGREGATE) and multi-key EXISTS

- lib/hash.js
- package.json
- test/redis-mock.hash.test.js
> Add support for deleting multiple fields from a hash

- README.md
- lib/hash.js
- lib/redis-mock.js
- package.json
- test/redis-mock.hash.test.js
I needed the HSCAN, so I mocked it out using the existing SCAN implementation as a starting point. 
Not sure about the version bump here - looks like it's `0.30.0` at NPM but `0.29.0` in master, so maybe master is behind and this needs a bigger version bump.
Thanks for taking a look!
> add HSCAN method to the client, update docs, bump package version

- README.md
- lib/list.js
- lib/multi.js
- lib/redis-mock.js
- test/redis-mock.list.test.js
> Introducing support for LREM

- .travis.yml
- README.md
- lib/hash.js
- lib/helpers.js
- lib/keys.js
- lib/list.js
- lib/pubsub.js
- lib/redis-mock.js
- lib/set.js
- lib/sortedset.js
- lib/strings.js
- package.json
- test/redis-mock.batch.test.js
- test/redis-mock.connection.test.js
- test/redis-mock.hash.test.js
- test/redis-mock.keys.test.js
- test/redis-mock.list.test.js
- test/redis-mock.multi.test.js
- test/redis-mock.pubsub.test.js
- test/redis-mock.server.test.js
- test/redis-mock.set.test.js
- test/redis-mock.sortedset.test.js
- test/redis-mock.strings.test.js
- test/redis-mock.test.js
Added missing methods for my own tests & did some cleanup on the way.
> Add DECR & DECRBY methods

- lib/multi.js
- test/redis-mock.multi.test.js
> add missing decr commands

- lib/pubsub.js
- lib/redis-mock.js
- package-lock.json
- test/redis-mock.batch.test.js
- test/redis-mock.connection.test.js
- test/redis-mock.hash.test.js
- test/redis-mock.keys.test.js
- test/redis-mock.list.test.js
- test/redis-mock.multi.test.js
- test/redis-mock.pubsub.test.js
- test/redis-mock.server.test.js
- test/redis-mock.set.test.js
- test/redis-mock.sortedset.test.js
- test/redis-mock.strings.test.js
- test/redis-mock.test.js
Connects-to: #95 
Change-type: patch
Signed-off-by: Giovanni Garufi <nazrhom@gmail.com>
> add optional callback to quit() (#95)

- lib/list.js
- lib/multi.js
- lib/redis-mock.js
- test/redis-mock.list.test.js
- test/redis-mock.multi.test.js
- this doesnt create any new functionality, it just utilizes the existing pop and push functions
- tests should cover all the use cases for the function
> feature(rpoplpush): added rpoplpush to list functions and multi + tests

- lib/keys.js
- lib/redis-mock.js
- test/redis-mock.keys.test.js
Adds support for PERSIST command and comes with tests to validate behavior.
See #104 and #117
> Add support for PERSIST command (with tests)

- lib/multi.js
- test/redis-mock.multi.test.js
> added renamenx to multi commands, added testcase

- lib/hash.js
- test/redis-mock.hash.test.js
fixing: https://github.com/yeahoffline/redis-mock/issues/152
> fixing the bug report - #152

- lib/client/multi.js
- lib/client/redis-client.js
- lib/helpers.js
- lib/server/hash.js
- lib/server/keys.js
- lib/server/list.js
- lib/server/redis-db.js
- lib/server/set.js
- lib/server/sortedset.js
- lib/server/strings.js
the function is used all over the place. At this point it doesn't fee like it's specific to any single class
> moved the callCallback to the helper functions

- lib/client/args/argParsers.js
- lib/client/redis-client.js
- lib/errors.js
- lib/index.js
- lib/server/redis-db.js
- lib/server/script.js
- package-lock.json
- package.json
- test/client/redis-mock.script.test.js
- test/helpers.js
introducing the supporting methods for rsmq
> WIP: added script debug support
