yeahoffline/redis-mock

- README.md
- lib/keys.js
- lib/redis-mock.js
- lib/strings.js
- test/redis-mock.keys.test.js
- test/redis-mock.strings.test.js
This patch enables the EXPIRE command to accept timeouts greater than (2**31)-1 msec, which is a limitation of JavaScript's setTimeout command, but not a limitation of Redis.
> EXPIRE now accepts values over 2**31-1 msec

- lib/helpers.js
- lib/keys.js
- lib/pubsub.js
- lib/redis-mock.js
- package.json
- test/redis-mock.helpers.test.js
- test/redis-mock.pubsub.test.js
In order to leverage pattern matching in `keys`, I moved the function `patternToRegex` out to a separate helpers.js file, so I could also use it in pubsub.js. I have added a lot of tests around `patternToRegex` to make sure it behaves well in many cases. Haven't yet filtered away functionality for special characters regex, like `\w`, which shouldn't match anything special in Redis.
Added psubscribe and punsubscribe functionality to match http://redis.io/commands/PSUBSCRIBE.
> Added support for psubscribe and punsubscribe

- lib/hash.js
- lib/redis-mock.js
- package.json
- test/redis-mock.connection.test.js
- test/redis-mock.hash.test.js
- test/redis-mock.keys.test.js
- test/redis-mock.list.test.js
- test/redis-mock.pubsub.test.js
- test/redis-mock.server.test.js
- test/redis-mock.set.test.js
- test/redis-mock.strings.test.js
- test/redis-mock.test.js
Psubscribe is a little different.
.end() without the flush flag causes a warning.
HINCRBY is slightly odd about returning the result as an integer instead of a string.
> Upgrading to latest version of node_redis

- lib/hash.js
- lib/redis-mock.js
- test/redis-mock.hash.test.js
- test/redis-mock.strings.test.js
node_redis supports a single array argument while calling hmset. See inlined comments for more details. Some of the comments might be overkill. Just let me know if you want me to remove them, or feel free to edit this PR.
- This straight up copies the same exact argument parsing from the node_redis hmset version. This moves the argument parsing into RedisClient.hmset and cleans up hmset in the hash module.
- Adds tests to support change. Also discovered some issues with existing test cases around hincrbyfloat, hsetnx, and setex.
> Refactor hmset argument parsing

- lib/helpers.js
- lib/list.js
- lib/redis-mock.js
- lib/sortedset.js
- test/redis-mock.list.test.js
This changes the argument parsing for LPUSH and RPUSH so the client methods support an array as the first argument, like this:
```
lpush(['key1', 'v', 'v2'], callback);
or
rpush(['key2', 'v', 'v2'], callback);
```
This change also refactors previous code into the helpers module for easier reuse.
> LPUSH and RPUSH

- README.md
- lib/multi.js
- lib/redis-mock.js
- test/redis-mock.multi.js
-) fixing #24 - ordering of multi means chaining of the queued commands
-) adds the discard keyword to multi
-) fixes empty queue calls
> Various fixes to multi

- lib/multi.js
- test/redis-mock.multi.js
The added test would fail only on redis-mock without the rest of the change :-) This is a bug I realized I introduced in #33, but now there's a regression test.
> Fixing atomicity of multis.

- lib/set.js
- test/redis-mock.set.test.js
Fixes:
```
TypeError: Cannot read property 'value' of undefined
at RedisClient.exports.sismember (/node_modules/redis-mock/lib/set.js:83:41)
at RedisClient.sismember.RedisClient.SISMEMBER (/node_modules/redis-mock/lib/redis-mock.js:571:26)
```
> Fix error in SISMEMBER when target key is unset

- Makefile
- lib/keys.js
- lib/multi.js
- lib/redis-mock.js
- test/redis-mock.keys.test.js
Current implementation misses the [PTTL command](https://redis.io/commands/pttl), which returns the TTL in milliseconds. 
I wasn't able to run the `make check-tests` command locally as I don't have any Redis locally installed. Yet, the `make test` command works.
> [RFR] Add support for PTTL

- lib/multi.js
- lib/redis-mock.js
for issue #42.
I use bluebird for Async function, but cannot Promisify exec function.
According to redis-doc, Promissify exec function  will be the following code.
> bluebird.promisifyAll(redis.Multi.prototype);
There is no prototype in multi of redis-mock, so please open Multi.
Best regards,
> #42 exports Multi module for promisify exec function

- lib/sortedset.js
- test/redis-mock.sortedset.test.js
First sort using the score
Then sort alphabetically
The issue was that the mock tests did not take into account multi digit scores so they pass. The mock code uses strings which means it will incorrectly compare "1" and "10" for example.
**NOTE**
This only tests zrevrange. If `10, 'm10'` and `10, 'm11'` are added to other sorted tests they fail. While this change is testing the sort overall via zrevrange, other tests should be eventually updated to account for this change as well. 
Given following set:
```
1, 'm1',
2, 'm2',
3, 'm3',
1.1, 'm1.1',
1.2, 'm1.2',
1.3, 'm1.3',
1.4, 'm1.4',
1.5, 'm1.5',
10, 'm10',
10, 'm11'
```
Mock was returning:
```
[
"m3",
"3",
"m2",
"2",
"m11",
"10",
"m10",
"10",
"m1.5",
"1.5",
"m1.4",
"1.4",
"m1.3",
"1.3",
"m1.2",
"1.2",
"m1.1",
"1.1",
"m1",
"1"
]
```
Redis …
> fix(sortedSet): sort correctly

- lib/redis-mock.js
- test/redis-mock.strings.test.js
The redis set function allows parameters to be passed as an array.
However, the special snowflake converting the object passed as a second parameter through toString() has to be handled as well.
Note: that behaviour will be removed in a future version of redis (if not already done)
> Allow documented parameters to the redis SET function

- Makefile
- lib/item.js
- lib/redis-mock.js
- lib/strings.js
- test/helpers.js
- test/redis-mock.connection.test.js
- test/redis-mock.hash.test.js
- test/redis-mock.item.test.js
- test/redis-mock.keys.test.js
- test/redis-mock.list.test.js
- test/redis-mock.multi.js
- test/redis-mock.pubsub.test.js
- test/redis-mock.server.test.js
- test/redis-mock.set.test.js
- test/redis-mock.sortedset.test.js
- test/redis-mock.strings.test.js
- test/redis-mock.test.js
Add support for setting/getting Buffers for basic string operations. This is compatible with node_redis where `detect_buffers` is set to true.
* Add `RedisBuffer` item type.
* Allow buffers for `get`, `set`, `getset`, `mget`, `mset`.
* If given a buffer in `set`, it is sent to Redis untouched (no call to `toString()`).
* If given a buffer for the key in `get`, it returns a buffer for the value. If given a string, it returns a string. This is the same regardless of the type of value originally stored in the cache. (This matches the behavior of node_redis.)
* Refactor `mget` to use `get` for consistent behavior.
* Refactor  tests to use `beforeEach` and `afterEach` for proper setup and teardown of cache.
* Add ability to set the redis instance to use when running `make check-tests` by …
> Add support for buffers for string operations

- lib/redis-mock.js
- test/redis-mock.pubsub.test.js
According to official documentation (https://github.com/NodeRedis/node_redis#pmessage-pattern-channel-message), the callback function in `.on('pmessage', callback)` should be called with the channel as second argument but was being called with the pattern.
> Fixed callback parameters on 'pmessage' event

- README.md
- lib/redis-mock.js
- test/redis-mock.test.js
This adds a mock for the `duplicate` method.
#63
> `duplicate()` missing function.

- lib/redis-mock.js
- package-lock.json
- package.json
- test/redis-mock.test.js
Add a `.connected` property to match the actual RedisClient as seen here:
https://github.com/NodeRedis/node_redis/blob/04a09aa2ffcbae9f380b61a4afe15badfe5be5ef/index.js#L90
Default it to `false` until we emit `ready`, then set to `true`
- Added tests to verify
- npm version bump to 0.32.0
> Add connected prop

- lib/redis-mock.js
- test/redis-mock.strings.test.js
+ `redis-mock` is going to crash if calling `set('key', null)`
- `(null || undefined).toString()` got a fatal error
- `String(null || undefined)` is a good way to fix it
+ Error
```js
should set `null` as value:
TypeError: Cannot read property 'toString' of null
at parseArguments (/Users/danielssun/Projects/redis-mock/lib/redis-mock.js:39:29)
at RedisClient.set.RedisClient.SET (/Users/danielssun/Projects/redis-mock/lib/redis-mock.js:353:16)
at context.<anonymous> (/Users/danielssun/Projects/redis-mock/test/redis-mock.strings.test.js:47:7)
at Test.Runnable.run (/Users/danielssun/Projects/redis-mock/node_modules/mocha/lib/runnable.js:233:15)
at Runner.runTest (/Users/danielssun/Projects/redis-mock/node_modules/mocha/lib/runner.js:387:10)
at …
```
> fixed: set nullPointer

- lib/redis-mock.js
This is necessary when you promisify the publish in test codes.
> Add callback support for the publish command.

- package.json
Add "files" attributes for npm to only pack necessary files.
This is can reduce package size a lot under `node_modules`.
see https://docs.npmjs.com/misc/developers
> Add files attributes for npm to reduce package size

- lib/redis-mock.js
- lib/set.js
- test/redis-mock.set.test.js
PR for issue #83
Adds support for members to be passed as arrays instead of arguments.
> add support for arguments as array for sadd and srem methods

- lib/redis-mock.js
This PR solves an issue where the `callback` argument was an array and not a function. 
I haven't had time to investigate why the first argument to `_callCallback` was an array and not a function, however this fixes the issue for us in the short term. 
A clue is that we are using redis-mock as a mock for https://github.com/mmkal/handy-redis. I believe the issue lies in the fact that handy-redis works with promises and not callbacks. This means that the redis method calls will not have a final callback argument.
> Check that callback is actually a function before calling it

- test/redis-mock.strings.test.js
Fixes #118 
Changed calls from `new Buffer(<string>)` to `Buffer.from(<string>)`.
> Change deprecated buffer creation

- lib/redis-mock.js
When doing a promisified client.get, redis-mock fails with:
```
/node_modules/redis-mock/lib/redis-mock.js:424
callback(err, "OK");
^
TypeError: callback is not a function
at /node_modules/redis-mock/lib/redis-mock.js:424:19
at /node_modules/redis-mock/lib/redis-mock.js:86:9
at processTicksAndRejections (internal/process/next_tick.js:74:9)
```
Resolved by using the _callCallback wrapper to make sure the callback is actually a function
> Fix callback issue

- README.md
- lib/multi.js
`zrevrangebyscore` is inaccesible from the mock class. Added to multi to allow usage.
> Added zrevrangebyscore to multi.js

- lib/hash.js
- test/redis-mock.hash.test.js
Passing an empty array for the keys should produce an error to replicate node_redis behavior.
Currently, it just doesn't call the supplied callback, which causes code to hang.
> Replicated error behavior between node_redis, and redis_mock

- lib/redis-mock.js
- test/redis-mock.strings.test.js
The real node-redis client supports the ttl argument as string:
```javascript
const client = createClient()
client.set("foo", "bar", "EX", "10")
```
The mock client doesn't.
Fixed this and added a test case for it.
> set() method: Support ttl argument specified as string

- lib/redis-mock.js
- test/redis-mock.test.js
- Added a `ready` property to match the actual RedisClient (https://github.com/NodeRedis/node-redis/blob/master/index.js#L371). `false` by default, `true` when `ready` is sent.
- Added two tests.
Similar to https://github.com/yeahoffline/redis-mock/pull/92.
> Add a ready property and tests

- lib/set.js
- test/redis-mock.set.test.js
this fix should slice the array copy for set > smembers result instead of returning a reference to the set.value. It prevents bugs when you iterate over the set. Removing or adding items in sequence and the underlying array changing causes for the iterator to obtain incorrect current index or array length.
> Make smembers result copy

- README.md
Added usage example to make the redis-mock work in jest.
Some of the less advanced developers will surely have a hard time figuring out how to use the mock, unless you show them how to do it step by step.
> Added a usage example

- .travis.yml
as the actual redis library supports Node 6, redis-mock should stay compatible back to Node 6 as well. Adding the travis configuration to ensure test execution on Node 6
> Adding the travis configuration to ensure test execution on Node 6

- .eslintrc
- lib/ArgumentParser.js
- lib/argParsers.js
- lib/keys.js
- lib/redis-mock.js
- lib/set.js
- package-lock.json
- package.json
- test/redis-mock.ArgumentParser.test.js
- test/redis-mock.batch.test.js
- test/redis-mock.keys.test.js
- test/redis-mock.multi.test.js
- test/redis-mock.set.test.js
- test/redis-mock.strings.test.js
The PR contains the following changes:
* updating the engine version to 6, as this is the version currently supported in the actual `redis` module: https://github.com/NodeRedis/node-redis/blob/master/package.json#L46
* Since using Node 6, I took into use features like `let`, `const`, `class` and arrow functions
* Making the optional parameters of SCAN and SSCAN actually optional. Before it required the MATCH parameter to always be there.
* Fixing, related issue that was already reported a long ago: https://github.com/yeahoffline/redis-mock/issues/130
* Confirmed that the reporter was right and fixed: https://github.com/yeahoffline/redis-mock/issues/129 which was also quite closely related
* fixing a few tests that were making sure that we continue following the wrong behaviour. If you SET …
> Fixing optionality for SCAN and SET
